# Generated by Django 4.2.5 on 2023-10-05 17:17

from django.db import migrations, models
import django.db.models.deletion
import test_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='department',
            field=models.ForeignKey(help_text='Выберите отдел', on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='Имя отдела'),
        ),
        migrations.AlterField(
            model_name='chief',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='chief',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(verbose_name='описание отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Введите название отдела', max_length=150, primary_key=True, serialize=False, verbose_name='Имя отдела'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, help_text='Введите имя', max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Введите имя', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(help_text='Введите номер команды', on_delete=django.db.models.deletion.CASCADE, to='test_django.team', verbose_name='Номер команды'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chief',
            field=models.ForeignKey(help_text='Выберите начальника отдела', on_delete=django.db.models.deletion.CASCADE, to='test_django.chief', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(help_text='Введите дату сдачи', verbose_name='Срок сдачи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ForeignKey(help_text='Выберите сотрудника', on_delete=django.db.models.deletion.CASCADE, to='test_django.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='project',
            name='evaluation',
            field=test_django.models.IntegerRangeField(help_text='Введите оценку за проект от 0 до 10', verbose_name='Оценка проекта'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Введите название команды', max_length=20, verbose_name='Имя команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='number',
            field=test_django.models.IntegerRangeField(help_text='Введите номер команды', verbose_name='Номер группы'),
        ),
        migrations.AlterModelTable(
            name='chief',
            table='Chief',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
    ]
