# Generated by Django 4.2.5 on 2023-10-10 15:18

from django.db import migrations, models
import django.db.models.deletion
import test_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0007_alter_employee_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number',
            field=test_django.models.IntegerRangeField(default=1, help_text='Введите номер проекта', verbose_name='Номер проекта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(help_text='Введите название команды', on_delete=django.db.models.deletion.CASCADE, to='test_django.team', verbose_name='Имя команды'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chief',
            field=models.ForeignKey(help_text='Выберите начальника отдела', on_delete=django.db.models.deletion.CASCADE, to='test_django.chief', verbose_name='Начальник'),
        ),
    ]
