# Generated by Django 4.2.5 on 2023-11-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0008_project_number_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='chief',
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('name_office', models.CharField(help_text='Введите название офиса', max_length=100, primary_key=True, serialize=False, verbose_name='Название офиса')),
                ('chief', models.ForeignKey(help_text='Выберите начальника отдела', on_delete=django.db.models.deletion.CASCADE, to='test_django.chief', verbose_name='Начальник')),
                ('team', models.ManyToManyField(to='test_django.team')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='office',
            field=models.ForeignKey(db_column='office', default='Золотое яблоко', help_text='Введите название офиса', on_delete=django.db.models.deletion.CASCADE, to='test_django.office', verbose_name='Офис'),
        ),
    ]
