# Generated by Django 4.2.5 on 2023-11-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0009_remove_project_chief_office_project_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='office',
        ),
        migrations.AddField(
            model_name='project',
            name='chief',
            field=models.ForeignKey(default='Шеф1', help_text='Введите имя начальника', on_delete=django.db.models.deletion.CASCADE, to='test_django.chief', verbose_name='Начальник'),
        ),
    ]
