# Generated by Django 4.2.5 on 2023-11-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0013_project_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='office',
            field=models.ForeignKey(blank=True, db_column='office', help_text='Введите название офиса', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_django.office', verbose_name='Офис'),
        ),
    ]
