# Generated by Django 4.2.5 on 2023-12-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0018_alter_employee_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Введите имя', max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(help_text='Введите название команды', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_django.team', verbose_name='Имя команды'),
        ),
    ]
